import Header from "./_components/Header"
import Footer from "./_components/Footer"
import { Metadata } from "next"

export const metadata:Metadata = {
  title: {
    absolute : 'root',
    default : 'nextjs tutorial',
    template : '%s template'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
